apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: dev
  source:
    repoURL: https://github.com/MichaelGit-beep/argoapp1.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: app1
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true 
      prune: true